name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  publish:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/gradle-minecraft-publish.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}
    secrets:
      curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}